version: "3.7"
services:
  db:
    image: postgres:12.0
    ports:
      - "5432:5432"
    networks:
      - jep-surveyor-graphql_default

  # tests:
  #   volumes:
  #     - ./_build:/tmp_build
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_HOST: db
  #   entrypoint: mix test

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
    entrypoint: bin/server
    networks: 
      - jep-surveyor-graphql_default

networks:
  jep-surveyor-graphql_default:
    external: true
