version: "3.7"
services:
  db:
    image: postgres:12.0
    ports:
      - "5432:5432"

  tests:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
    entrypoint: mix test

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
    entrypoint: iex -S mix
    # entrypoint: mix run --no-halt -b 0.0.0.0
